### PR TITLE
Tom

### PR DESCRIPTION
**Pull request by tomstoten**
This version should work with the updated JSBML

### CODE REVIEW

**Comment by cjmyers** [comment]
@tomstoten Looks like you have some conflicts to resolve.

**Review by tomstoten — COMMENTED** [review]
MyersResearchGroup/bioSimPortal:main now up to date with SynBioHub/Plugin-Download-iBioSim:Tom

**Comment by cjmyers** [comment]
Still see conflicts that need resolving.

**Comment by cjmyers** [comment]
@tomstoten Looks good now

**Comment by tomstoten** [comment]
Great, I just made another pull request to the Plugin-Download-iBioSim main
branch as well.

**Pull request merged**
